update current xcodeproj's - todo: refactor to oF's current layout..
	OF_WARNING:  texture not bound for character -- line 656 in apps/examples/eventsExample/../../../libs/openFrameworks/graphics/ofTrueTypeFont.cpp

	addons/ofx3dutils/ofx3D.cpp:34: error: 'glutSolidTeapot' was not declared in this scope
	addons/ofx3dutils/ofx3D.cpp:54: error: 'glutSolidCube' was not declared in this scope
	addons/ofx3dutils/ofx3D.cpp:78: error: 'glutSolidSphere' was not declared in this scope
	addons/ofx3dutils/ofx3D.cpp:101: error: 'glutSolidSphere' was not declared in this scope